name: batch-inference-facebook-bart-large-cnn_nb

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/batch-inference-facebook-bart-large-cnn_nb.yaml
env:
  model_name: facebook-bart-large-cnn
  model_version: 4
jobs:
  batch-inference-facebook-bart-large-cnn_nb:
    runs-on: self-hosted
    steps:
      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZ_SYSTEM}}
      - name: run foundation-models/system/inference/summarization/summarization-batch-endpoint.ipynb
        run: |
            papermill -k python summarization-batch-endpoint.ipynb summarization-batch-endpoint.output.ipynb -p model_name "${{ env.model_name }}" -p model_version "${{ env.model_version }}"
        working-directory: sdk/python/foundation-models/system/inference/summarization
      - name: upload notebook's working folder as an artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: summarization-batch-endpoint
          path: sdk/python/foundation-models/system/inference/summarization