name: real-time-inference-bert-large-uncased_nb

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/real-time-inference-bert-large-uncased_nb.yaml
env:
  model_name: bert-large-uncased
  model_version: 4
jobs:
  real-time-inference-bert-large-uncased_nb:
    runs-on: self-hosted
    steps:
      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZ_SYSTEM}}
      - name: run foundation-models/system/inference/fill-mask/fill-mask-online-endpoint.ipynb
        run: |
            papermill -k python fill-mask-online-endpoint.ipynb fill-mask-online-endpoint.output.ipynb -p model_name "${{ env.model_name }}" -p model_version "${{ env.model_version }}"
        working-directory: sdk/python/foundation-models/system/inference/fill-mask
      - name: upload notebook's working folder as an artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: fill-mask-online-endpoint
          path: sdk/python/foundation-models/system/inference/fill-mask