name: real-time-inference-microsoft-deberta-large-mnli_nb

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/real-time-inference-microsoft-deberta-large-mnli_nb.yaml
env:
  model_name: microsoft-deberta-large-mnli
  model_version: 4
jobs:
  real-time-inference-microsoft-deberta-large-mnli_nb:
    runs-on: self-hosted
    steps:
      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZ_SYSTEM}}
      - name: run foundation-models/system/inference/text-classification/text-classification-online-endpoint.ipynb
        run: |
            papermill -k python text-classification-online-endpoint.ipynb text-classification-online-endpoint.output.ipynb -p model_name "${{ env.model_name }}" -p model_version "${{ env.model_version }}"
        working-directory: sdk/python/foundation-models/system/inference/text-classification
      - name: upload notebook's working folder as an artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: text-classification-online-endpoint
          path: sdk/python/foundation-models/system/inference/text-classification