name: self-hosted-runner-test

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/self-hosted-runner-test.yaml
jobs:
  runner-test:
    runs-on: scale-test-ep
    steps:
    - name: check-out-repo-step
      uses: actions/checkout@v2
    - name: azure-login-step
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CRED}}
    - name: pip-install-azure-ai-ml
      run: pip install azure-ai-ml 