name: TRIGGER_TESTS

on: 
  workflow_dispatch:
    inputs:
      test_queue:
        default: huggingface-all

jobs:
  start-tests-job:
    runs-on: ubuntu-latest
    steps:
    - name: check-out-repo-step
      uses: actions/checkout@v2
    - name: start-tests-step
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ${{ test_queue}}
        for file in `ls -1`  
        do  
          gh workflow run `cat $file | head -n 1`
        done    
      working-directory: tests/config/queue